version: '3'

# services:
    # app:
    #     container_name: abcTeamContainer
    #     image: nhlcoding
    #     build: .
    #     ports:
    #         - '3000:3000'
    #     depends_on:
    #         - db

    # db:
    #     container_name: abcTeamDB
    #     image: postgres
    #     volumes:
    #         - ./tmp/db:/var/lib/postgresql/data
    #     ports:
    #         - '5433:5432'
    #     environment:
    #         - POSTGRES_PASSWORD=password
    #         - POSTGRES_USER=abcTeam
    #         - POSTGRES_DB=abcDatabase

services:
  postgres:
    image: postgres:12
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data

  pg-admin:
    image: dpage/pgadmin4:6
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@email.com
      - PGADMIN_DEFAULT_PASSWORD=admin
      - PGADMIN_LISTEN_PORT=5050

    ports:
      - "5050:5050"

volumes:
  data: