# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - abc-summer

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      CONNECTION_STRING: ${{ secrets.CONNECTION_STRING }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'


      - name: Create .env file
        run: |
          echo "CONNECTION_STRING=${CONNECTION_STRING}" > .env

      - name: Display .env content
        run: cat .env
        
          
      - name: View directory
        run: | 
          ls


      - name: npm install, build, and test
        run: |
          npm install
          npm run test --if-present
  
  build:
    runs-on: 'ubuntu-latest'
    needs: test

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_84b6322cb2314924b29f3396e2b71da5 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_8779f65d2f044a338a93b5daf9e6cc8b }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_84b6322cb2314924b29f3396e2b71da5 }}/abc-summer:${{ github.sha }}
        file: ./Dockerfile
        build-args: |
          ENV_VARIABLE=${{ secrets.CONNECTION_STRING }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'abc-summer'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_0929f86fc14f4edb9031949fdf9786ea }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_84b6322cb2314924b29f3396e2b71da5 }}/abc-summer:${{ github.sha }}'
